<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Incidencia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get incidencia by id
     */
    function get_incidencia($id)
    {
        return $this->db->get_where('incidencias',array('id'=>$id))->row_array();
    }

    //Comprueba si la incidencia que se quiere editar pertenece a ese usuario 
    function check_edit_usuario($id_incidencia)
    {
        $this -> db -> select('id_usuario');
        $this -> db -> from('incidencias');
        $this -> db -> where('id', $id_incidencia);
        $this -> db -> limit(1);
 
        $query = $this -> db -> get();
        return $query->row_array();
    }

    //Comprueba si la incidencia que se va a dar por resuelta esta asignada a ese tecnico para que otro no se la de por resuelta
     function check_incidencia_tecnico_asignada($id_incidencia)
    {
        $this -> db -> select('id_tecnico');
        $this -> db -> from('incidencias');
        $this -> db -> where('id', $id_incidencia);
        $this -> db -> limit(1);
 
        $query = $this -> db -> get();
        return $query->row_array();
    }
    
    /*
     * Get mis incidencias creadas por mi 
     */
    function get_my_incidencias($id)
    {
        $this -> db -> select('incidencias.id,nombre,apellidos,departamento,titulo,descripcion,estado,fecha');
        $this -> db -> from('incidencias');
        $this -> db -> join('usuarios', 'incidencias.id_usuario = usuarios.id');
        $this -> db -> where('incidencias.id_usuario', $id);
        $this->db->not_like('estado', 'resuelta');
 
        $query = $this -> db -> get();
        return $query->result_array();   

          }

    //Get las incidencias que estan sin asignar en el sistema      
    function get_sin_asignar()
    {
        $this -> db -> select('incidencias.id,nombre,apellidos,departamento,titulo,descripcion,estado,fecha');
        $this -> db -> from('incidencias');
        $this -> db -> join('usuarios', 'incidencias.id_usuario = usuarios.id');
        $this -> db -> where('incidencias.estado', 'registrada');
 
        $query = $this -> db -> get();
        return $query->result_array(); 

    }

      //Get las incidencias que tiene asignadas un tecnico
      function get_incidencia_tecnico($id)
    {
        $this -> db -> select('incidencias.id,nombre,apellidos,departamento,titulo,descripcion,estado,fecha');
        $this -> db -> from('incidencias');
        $this -> db -> join('usuarios', 'incidencias.id_usuario = usuarios.id');
        $this -> db -> where('incidencias.id_tecnico', $id);
        $this -> db -> where('incidencias.estado', 'asignada');

        $query = $this -> db -> get();
        return $query->result_array(); 

        /*select incidencias.id,usuario.nombre as 'Usuario_nombre',usuario.apellidos as 'usuario_apellidos',usuario.departamento as 'usuario_departamento',tecnico.nombre as 'tecnico_nombre',tecnico.apellidos as 'tecnico_apellidos',incidencias.titulo,incidencias.descripcion,incidencias.estado,incidencias.fecha 
        from incidencias 
        inner join usuarios usuario on incidencias.id_usuario = usuario.id 
        inner join usuarios tecnico on incidencias.id_tecnico = tecnico.id  
        where incidencias.estado = 'asignada' order by incidencias.fecha desc*/

    }


    //Get todas las incidencias asignadas
    function get_incidencias_asignadas(){

        $this -> db -> select('incidencias.id,nombre,apellidos,departamento,titulo,descripcion,estado,fecha');
        $this -> db -> from('incidencias');
        $this -> db -> join('usuarios', 'incidencias.id_usuario = usuarios.id');
        $this -> db -> order_by('incidencias.fecha DESC', 'usuarios.nombre');
        $this -> db -> where('incidencias.estado', 'asignada');
        

        $query = $this -> db -> get();
        return $query->result_array();

        $this -> db -> select('nombre,apellidos');
        $this -> db -> from('incidencias');
        $this -> db -> join('usuarios', 'incidencias.id_tecnico = usuarios.id');
        $this -> db -> order_by('incidencias.fecha DESC', 'usuarios.nombre');
        $this -> db -> where('incidencias.estado', 'asignada');
        

        $query1 = $this -> db -> get();
        return $query1->result_array();
    }


    //Get numero de incidencias que tiene asignado cada tecnico
     function get_numero_incidencia_tecnico()
    {
        $this -> db -> select('usuarios.nombre,usuarios.apellidos, count(incidencias.id) as numero');
        $this -> db -> from('usuarios');
        $this -> db -> join('incidencias', 'usuarios.id = incidencias.id_tecnico', 'left');
        $this -> db -> where('usuarios.rol', 'tecnico');
        $this -> db -> group_by('incidencias.id_tecnico');
 
        $query = $this -> db -> get();
        return $query->result_array(); 

    }

    
    /*
     * function to add new incidencia
     */
    function add_incidencia($params)
    {
        $this->db->insert('incidencias',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update incidencia
     */
    function update_incidencia($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('incidencias',$params);
    }
    
    //Obtiene la lista con todos los tecnicos del sistema
    function get_tecnicos()
    {   
       return $this->db->get_where('usuarios', "rol='tecnico'")->result_array();
    }

    /*
     * function to delete incidencia
     */
    function delete_incidencia($id)
    {
        $this->db->delete('incidencias',array('id'=>$id));
    }

    //Asigna una incidencia a un usuario
    function asignar_incidencia($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('incidencias',$params);
    }
}

