<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by id
     */
    function get_usuario($id)
    {
        return $this->db->get_where('usuarios',array('id'=>$id))->row_array();
    }

    //Funcion que comprueba en login si existe usuario y contraseña correcta
    function login($email, $password)
    {
        $this -> db -> select('id, email, password, rol');
        $this -> db -> from('usuarios');
        $this -> db -> where('email', $email);
        $this -> db -> where('password', MD5($password));
        $this -> db -> limit(1);
 
        $query = $this -> db -> get();
 
         if($query -> num_rows() == 1)
         {
             return $query->result();
         }
         else
         {
             return false;
         }
    }
    
    //Obtiene los datos del usuario para la seccion mi cuenta
    function mi_cuenta($id)
    {
        return $this->db->get_where('usuarios',array('id'=>$id))->row_array();
    }
    

    //Comprueba cuando se registra un nuevo usuario si existe ese email ya en el sistema
    function check_email($email)
    {
        $this -> db -> select('email');
        $this -> db -> from('usuarios');
        $this -> db -> where('email', $email);
        $this -> db -> limit(1);
 
        $query = $this -> db -> get();
 
        if($query -> num_rows() == 1)
        {
             return $result = 1;
        }
        else
        {
            return $result = 0;
        }
    }

    /*
     * Get all usuarios
     */
    function get_all_usuarios()
    {
        return $this->db->get('usuarios')->result_array();
    }
    
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuarios',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('usuarios',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($id)
    {
        $this->db->delete('usuarios',array('id'=>$id));
    }
}
